[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33636ff"

# Background color for the main content area.
backgroundColor = "#e5ece4"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
# textColor = "#fff"

[client]
toolbarMode = "minimal"